### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by eli-betito** [kovacsbalu/WazeRouteCalculator#14]
Can anyone help me figure out why I get this error only when I try to use Israel ?
```
Traceback (most recent call last):
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Below is my code,
```
import WazeRouteCalculator

from_address = 'Eilat, Israel'
to_address = 'Beersheba, Israel'
region = 'IL'

route = WazeRouteCalculator.WazeRouteCalculator(from_address, to_address, region)
route.calc_all_routes_info()
```
Thanks!

**Comment by lovato** [comment]
Well, I started having this issue today. The same code that was running on Friday.

**Comment by lovato** [comment]
#15 solves this.

**Comment by kovacsbalu** [comment]
Hi, so this problem caused by the waze server or need a fix in our wrc?

**Comment by kovacsbalu** [comment]
Ohh, let's check the fix :)

**Comment by kovacsbalu** [comment]
@lovato great! Thanks!

**Comment by eli-betito** [comment]
It's still not working for me.

**Comment by kovacsbalu** [comment]
Please wait for version 0.5 or download from github
[https://github.com/kovacsbalu/WazeRouteCalculator/archive/0.5.zip](url)

**Comment by eli-betito** [comment]
Thank you guys so much :-)

**Comment by kissscool** [comment]
Hello,

I have a error while using your amazing code. It was working few days ago.
Here is the error message :
"
File "C:\Waze API\lib\waze_route_calculator.py", line 99, in get_route
raise WRCError(response_json.get("error"))
WRCError: Internal Error
"

Any guess ?

Thanks
