### ISSUE TITLE
WazeRouteCalculator is not working

### ISSUE THREAD

**Issue by aquirin** [kovacsbalu/WazeRouteCalculator#22]
It seems now that https://www.waze.com/row-RoutingManager/routingRequest returns a 403 error. Is that only me?

**Comment by kovacsbalu** [comment]
Yes, when you open in browser. WazeRouteCalculator works well :)

**Comment by aquirin** [comment]
Ok but did you run it again? I am getting the error with the module not the
browser

Le mer. 12 sept. 2018 à 09:10, Kovács Bálint <notifications@github.com> a
écrit :

**Comment by kovacsbalu** [comment]
Sure, I double checked and is was ok. Can you please send more details? Output?
