### ISSUE TITLE
Request: Australia region

### ISSUE THREAD

**Issue by aetolus** [kovacsbalu/WazeRouteCalculator#24]
Hi,

Thanks for your work on this.

I was wondering if it would be possible for you to add Australia as a region in WazeRouteCalculator?

Thanks,

**Comment by kovacsbalu** [comment]
Hi @aetolus, region is used for base coords in search request. 
You can use WRC with EU/US...region code, but you should give exact address.
I will add AS if you want with Camberra base coords.:)

**Comment by kovacsbalu** [comment]
@ngshiheng Sure, can you please send me a base place coords?
