### ISSUE TITLE
Feature request: add option to choose whether car or motorcycle

### ISSUE THREAD

**Issue by cbrherms** [kovacsbalu/WazeRouteCalculator#31]
The waze api allows for a `vehicleType` param that accepts either `TAXI` or `MOTORCYCLE` and adjusts the route / expected travel time accordingly.

Could an optional variable please be added to the calculator that accepts one of these values?

**Comment by cbrherms** [comment]
Examples:

Manchester Piccadilly to Birmingham New street (England).


**Without:**
`https://www.waze.com/row-RoutingManager/routingRequest?from=x:-2.231219 y:53.477387&to=x:-1.898886 y:52.477901&at=0&returnJSON=true&returnGeometries=true&returnInstructions=true&timeout=60000&nPaths=1&options=AVOID_TRAILS:t`

```
{
    "response": {
...
        "totalRouteTime": 6624,
...
}
```
Time = 1 Hour, 50 Minutes and 23 Seconds


**Taxi:**
`https://www.waze.com/row-RoutingManager/routingRequest?from=x:-2.231219 y:53.477387&to=x:-1.898886 y:52.477901&vehicleType=TAXI&at=0&returnJSON=true&returnGeometries=true&returnInstructions=true&timeout=60000&nPaths=1&options=AVOID_TRAILS:t`

```
{
    "response": {
...
        "totalRouteTime": 6626,
...
}
```
Time = 1 Hour, 50 Minutes and 25 Seconds


**Motorcycle:**
`https://www.waze.com/row-RoutingManager/routingRequest?from=x:-2.231219 y:53.477387&to=x:-1.898886 y:52.477901&vehicleType=MOTORCYCLE&at=0&returnJSON=true&returnGeometries=true&returnInstructions=true&timeout=60000&nPaths=1&options=AVOID_TRAILS:t`

```
{
    "response": {
...
        "totalRouteTime": 6141,
...
}
```
Time = 1 Hour, 42 Minutes and 21 Seconds

**Comment by kovacsbalu** [comment]
Hi @cbrherms good feature. Thanks! I will ... :)

**Comment by cbrherms** [comment]
@kovacsbalu 
I've opened a PR #32 with the changes I believe gets this done. I don't think this should be a breaking change for anything, and while i've done my own testing here i've not written any tests for travis.

**Comment by kovacsbalu** [comment]
Thanks, for your PR. I will change a bit before next release. Default should no vehicleType in request.

**Comment by cbrherms** [comment]
Thanks :)
