### ISSUE TITLE
does this always return km?

### ISSUE THREAD

**Issue by ljmerza** [kovacsbalu/WazeRouteCalculator#33]
Seems to sometimes return imperial units depending on location. Are there any docs for this api endpoint?

**Comment by kovacsbalu** [comment]
Hi @ljmerza, can you please send an example?

**Comment by ljmerza** [comment]
I use home assistant and created a [waze-card](https://github.com/ljmerza/waze-card) for lovelace UI but am having trouble getting consistent units of measurement for all my users. My home assistant is setup for imperial units but when the waze component uses your library to get the distance it brings it back in kilometers. Other users are reporting it works correctly though. You can see here the distance is `24` but google maps says 15 miles. `24` is 15 mile in kilometers.

![image](https://user-images.githubusercontent.com/4085765/52959843-4abb1980-3365-11e9-803a-7e575e5f2f20.png)

**Comment by kovacsbalu** [comment]
I see. Maybe waze-card should convert to miles. WazeRouteCalculator has no option for unit, as I know waze api returns in km. But probably it depends on routing server.

**Comment by ljmerza** [comment]
Yeah that's my issue. It's not consistent. I initially did try to convert
in my card but if the data from your library isn't consistent then it
doesn't matter. At this point I'll just display the direct data that comes
from the waze library. Not much to do from there. Thanks!

**Comment by hmmbob** [comment]
After the fix for #35, you might get more stable results (as the routing server will be chosen based on the region you selected). You might be able to link km vs mi to the region selected in Home Assistant then for the Waze card.

**Comment by kovacsbalu** [comment]
@ljmerza can you please test with version 0.9?

**Comment by ljmerza** [comment]
Looks like there's a pull request to merge v0.9 into home assistant https://github.com/home-assistant/home-assistant/pull/21130

**Comment by hmmbob** [comment]
Expect it in HA 0.89
