### ISSUE TITLE
empty vehicleType causes empty response.

### ISSUE THREAD

**Issue by cbrherms** [kovacsbalu/WazeRouteCalculator#34]
https://github.com/kovacsbalu/WazeRouteCalculator/blob/5319b796a0e7fe5dba07b0c66b1313e408af63a4/WazeRouteCalculator/WazeRouteCalculator.py#L91

^ This being empty when vehicle_type is not defined causes an empty response. If it is included in the sent params it must contain a valid type of 'PRIVATE', 'TAXI', 'MOTORCYCLE', or 'ELECTRIC' (US and Canada region only).
[source](https://support.google.com/waze/answer/7579259?hl=en)

```
cbherms@Herms-PC:/mnt/d/Documents/GitHub/WazeRouteCalculator$ python example.py
From: Budapest, Hungary - to: Győr, Hungary
empty response
```

Admittedly I was unaware private and electric were accepted values, hence setting it to taxi, though i now also realise using taxi instead of private would skew routes as they can use bus lanes in some countries.

Either way, setting it to 'PRIVATE' if it is undefined will fix the above issue, unless you wish to have a check to see if the variable contains anything.
Also, including the full list of options including the note for Electric would be useful to others.

**Comment by kovacsbalu** [comment]
Thanks @cbrherms, I will fix it immediately.

**Comment by kovacsbalu** [comment]
Fixed!
