### ISSUE TITLE
This randomly seems to error on finding co-ords. 

### ISSUE THREAD

**Issue by SConaway** [kovacsbalu/WazeRouteCalculator#35]
This randomly seems to error on finding co-ords. Any ideas?

I'm in the US, trying to find a route with `to_address = '301 N Orange Grove Blvd, Pasadena, CA'`

**Comment by kovacsbalu** [comment]
Hi @SConaway, can you please test with [feat-searchserver-region](https://github.com/kovacsbalu/WazeRouteCalculator/tree/feat-searchserver-region) branch?

**Comment by SConaway** [comment]
That works much better. Now it just fails to find a route, but at least it's one more step.

**Comment by SConaway** [comment]
That works much better. Now it just fails to find a route, but at least it's one more step.

**Comment by mikeage** [comment]
Is it possible to merge feat-searchserver-region?

**Comment by kovacsbalu** [comment]
sure :)
