### ISSUE TITLE
Error not properly raised

### ISSUE THREAD

**Issue by Petro31** [kovacsbalu/WazeRouteCalculator#36]
Empty response is always raised in get_route when no servers return a result because if statement has an extra not.  Should be:
```
if response_json and 'error' in response_json:
```

I'd also argue that the error "empty response" should be changed to "no response from server"

Lastly, Why do these errors occur so much?  I added a debug statement in the loop to see responses and it seems like the waze api is always returning an 'error': 'Internal Error'.

**Comment by Petro31** [comment]
This issue will be resolved if we use https://github.com/kovacsbalu/WazeRouteCalculator/pull/37

**Comment by PlayedIn** [comment]
Can you please accept the PR?  Getting empty response constantly.
