### ISSUE TITLE
Enhancement: Unit conversion for time and distance

### ISSUE THREAD

**Issue by raman325** [kovacsbalu/WazeRouteCalculator#42]
It would be great if there was a way to specify distance and time units by passing in new parameters to `calc_route_info` and `calc_all_route_info`. I was thinking of using [pint](https://github.com/hgrecco/pint) to handle the unit conversions. I have an idea of how to implement this, just wanted to get your thoughts and see if it was worth the effort. The plan would be to add additional parameters to both functions but to keep the default values such that the expected output doesn't change.

Let me know what you think!

**Comment by raman325** [comment]
It was a quick enhancement so I proposed a PR here: https://github.com/kovacsbalu/WazeRouteCalculator/pull/43

**Comment by kovacsbalu** [comment]
Hi @raman325,
thanks for your PR. But, as you can see `calc_route_info` and `calc_all_route_info` returns only numbers without unit. So you can convert this after.
In other hand, I don't want to depend on 3rd party lib.

**Comment by raman325** [comment]
Fair enough, I actually came to the same conclusion after thinking about it, but kept the PR up since the work was already done
