### ISSUE TITLE
Vignette system not processed in EU (rp_subscription)

### ISSUE THREAD

**Issue by sretalla** [kovacsbalu/WazeRouteCalculator#45]
The changes on the waze site means that when routing in Europe, unless Vignettes are specified to cover toll roads, toll roads will not be used in the route regardless of the avoid_toll_roads selection.

In order to get it to work properly, you can either set preferences in the mobile app to indicate you have the vignette for the country(ies), or you can add &rp_subscription=* to the URL (or specify the country if you only have a vignette in one country), which works to see toll roads in the calculation.

What I can't work out is how to adjust the script to allow for this... I tried adding it in the url_options section, but no success there... please help as the route calculation is always using a longer route and hence useless.

**Comment by sretalla** [comment]
For example, this:
[Route without subscription](https://www.waze.com/livemap/directions?latlng=46.4729464%2C6.8365348&from=46.5517187%2C6.5628022&at=now)

vs this

[Route with subscription](https://www.waze.com/livemap/directions?latlng=46.4729464%2C6.8365348&from=46.5517187%2C6.5628022&at=now&rp_subscription=*)

**Comment by sretalla** [comment]
Although I understand why this could be viewed as a request for a new feature/enhancement to allow the specification of vignettes, I would argue that the current status with the API as it is produces a consistently wrong result which doesn't take into account the options with "toll roads", which are clearly the best and quickest, so for me it's an issue... anyway, I appreciate any help in order to make it better.

**Comment by kovacsbalu** [comment]
Hi @sretalla, I'll check it soon. BTW any PR with tests are welcomed.

**Comment by sretalla** [comment]
I'm certainly no coding expert and really don't know enough about how a PR works to submit one, but if I can get a little guidance on how the request builds the API (I can't decipher how the final URL is really put together), I would be happy to work on a way to include the &rp_subscription=* into it... maybe also allowing a variable to specify a country or list of countries for those who need that.

**Comment by sretalla** [comment]
I did a little digging and the format is &rp_subscription=vignette-switzerland (replace switzerland with other European countries as appropriate).

**Comment by sretalla** [comment]
Seems you can chain them together in the URL, like &rp_subscription=vignette-switzerland&rp_subscription=vignette-austria

**Comment by sretalla** [comment]
OK, so I created a version of the script that works...

What is needed is pretty much just to use subscription=* or subscription=vignette-country (also OK to add multiples) (rp_subscription=*, etc is needed in the live map site, but doesn't work in the routing servers for the API).

I added the line under url_options

            "at": time_delta,
            **"subscription": self.RP_SUBSCRIPTION["ALL"],**
            "returnJSON": "true",

And now I get correctly routed (timed) along the toll roads in Switzerland.

I guess the next improvement on top of that would be to allow for a list of countries, meaning that folks who have some vignettes but not others would also get the right answers too.

For my needs, the * is enough.

**Comment by sretalla** [comment]
I figured out how to use pull requests and made one.

Assuming the request is accepted, we're all done here (for now) since the subscription=* option is covered as long as avoid_toll_roads isn't set.

**Comment by sretalla** [comment]
Along the way to figuring this out, I saw some discussion about Mexico and a few other countries too.
In that discussion, ideas were floated around about keeping avoid_toll_roads separate from the vignettes, since it can happen that you want to avoid toll roads not covered by the vignettes you have specified. (they settled on having a setting for avoid_toll_roads and an all_vignettes setting without going into the possibility of having individual vignettes... I agree that it's really an edge case where you would use this script and need a crazy combination of different countries, toll roads and vignettes involved)
It was my assumption that most users of this script will just be happy to have the routes including toll roads covered by the vignette system when they opt not to avoid toll roads in general.

**Comment by sretalla** [comment]
I added test cases by copying and slightly modifying the cases for avoid_toll_roads, but it seems I don't understand the tests completely as I see messages about failing build... help would be appreciated.

**Comment by kovacsbalu** [comment]
> Along the way to figuring this out, I saw some discussion about Mexico and a few other countries too.
> In that discussion, ideas were floated around about keeping avoid_toll_roads separate from the vignettes, since it can happen that you want to avoid toll roads not covered by the vignettes you have specified. (they settled on having a setting for avoid_toll_roads and an all_vignettes setting without going into the possibility of having individual vignettes... I agree that it's really an edge case where you would use this script and need a crazy combination of different countries, toll roads and vignettes involved)
> It was my assumption that most users of this script will just be happy to have the routes including toll roads covered by the vignette system when they opt not to avoid toll roads in general.

Yes, Thats why I ask you in PR.

**Comment by sretalla** [comment]
As initially specified in the issue description, if I don't specify to avoid toll roads, but plan a route in Switzerland, no toll roads will be used since the current version of the script doesn't account for the vignette system which controls the toll roads in a bunch of countries in Europe.

In order to have the avoid toll roads option correctly behave for those countries, you need to specify that you have the appropriate vignette for the country you're navigating through.

At least in my use case, I'm happy to see the two things as the same and it results in toll roads not being avoided on my routes, which is my need/issue.

**Comment by sretalla** [comment]
@kovacsbalu Will you be accepting the PR?

**Comment by kovacsbalu** [comment]
see pr #46

**Comment by sretalla** [comment]
@kovacsbalu  I made your requested changes and submitted a new PR. Please accept it.
