### ISSUE TITLE
Toll roads avoided in some countries when avoid_toll_roads not set.

### ISSUE THREAD

**Issue by sretalla** [kovacsbalu/WazeRouteCalculator#48]
In some European countries (and maybe others), the vignette system is used for toll roads and the Waze API doesn't respect them as toll roads, rather as subscription roads, meaning without setting the avoid_toll_roads option to True, toll roads are avoided in those countries regardless.

A new option for subscription roads is needed.

**Comment by sretalla** [comment]
See PR #47 for the solution.

**Comment by sretalla** [comment]
@kovacsbalu will you be accepting the PR which was constructed as you requested with the subscription roads option?

**Comment by kovacsbalu** [comment]
Sure, I was on leave :)
