### ISSUE TITLE
Duplicate logging in HA

### ISSUE THREAD

**Issue by mikeage** [kovacsbalu/WazeRouteCalculator#50]
When using WazeRouteCalculator in HomeAssistant (and presumably elsewhere), certain lines are logged multiple times. For example:
```
From: 31.AAAA,34.BBBB - to: 31.CCCC,34.DDDD
2019-10-07 17:31:33 INFO (SyncWorker_7) [WazeRouteCalculator.WazeRouteCalculator] From: 31.AAAA,34.BBBB - to: 31.CCCC,34.DDDD
Start coords: (31.AAAA, 34.BBBB)
End coords: (31.CCCC, 34.DDDD)
Time 0.25 - 0.25 minutes, distance 0.04 - 0.04 km.
2019-10-07 17:31:33 INFO (SyncWorker_7) [WazeRouteCalculator.WazeRouteCalculator] Time 0.25 - 0.25 minutes, distance 0.04 - 0.04 km.
```
This seems to be because of:
```python
        if not len(self.log.handlers):
            self.log.addHandler(logging.StreamHandler())
```
Is there a reason why you do this?

**Comment by kovacsbalu** [comment]
Hi @mikeage, probably WazeRouteCalculator got two logger. One with debug and an other with info level. As I can see in HA source waze route calculator run with debug log. Can you please get some information about logger name or provide some example code?

**Comment by mikeage** [comment]
I think it's one logger with multiple handlers. There's the one that HA attaches and the one added in the snippet I pasted. The HA one is configured to output INFO (and has some formatting), whereas the one here doesn't do formatting and includes DEBUG.

I'm not sure why the HA handler doesn't show up in the `if` here, but this seems to be the issue. Maybe there's a better way? (truth is, I don't think modules should be adding their own handlers at all; if you have a __main__, you can call logging.basicConfig (or another initialization code there), but when you're being imported and called as a module in someone else's program, they should decide the logging).

**Comment by kovacsbalu** [comment]
Hi @mikeage, can you please check fix-logging branch?

**Comment by mikeage** [comment]
The fix-logging branch was a bit behind `master`, so I just cherry-picked the commit. Removing the log_lvl from `__init__` breaks the plugin, but if I keep that line, it seems ok. That said, you're using logging in a rather weird way... I'm not sure why you're attaching a null handler in the first place :-/

**Comment by kovacsbalu** [comment]
Yep, now synced with master and added log_lvl warning.
Weird way? Check... https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library

**Comment by mikeage** [comment]
Gotcha. I didn’t know about the recommendation for the null handler. Thanks! The note there about not putting other handlers, though, is what I first thought of.

**Comment by kovacsbalu** [comment]
Can I merge master and release v0.11?

**Comment by mikeage** [comment]
Looks good to me.

**Comment by mikeage** [comment]
Thanks!
