### ISSUE TITLE
Waze travel time in Slovakia (and other EU countries) not using highways

### ISSUE THREAD

**Issue by welo78** [kovacsbalu/WazeRouteCalculator#51]
Hello since the addition of vignettes for highways in 12.12. 2018 (I read this on waze forum). The route calculations for Slovakia (maybe other countries aswell) does not seem to be working properly. As I recall the waze travel time component uses waze's live map to calculate the best route. However for Slovakia it does not as you can see below. (No this has nothing to do with obstructions on the highway because the mobile app reports it correctly.)

Another guy already pointed to this in this issue of home assistant:
[Issue #25964](https://github.com/home-assistant/home-assistant/issues/25964)

This route should take no more than 90 minutes.
![image](https://user-images.githubusercontent.com/42773655/66575615-7f8b1380-eb76-11e9-9f18-5e603b5446f4.png)

My question is is it possible to manually implement or push or maybe even tick boxes for highway vignettes (passes) so it can calculate the routes correctly ? Or is it possible to take the updated map (as a pointer of some sort) for slovakian region so it uses the correct one?

Here you can see the original live map which to this date has not been fixed to use highways. It seems like the developers missed inplementing highway permissions for Slovakian map.
![image](https://user-images.githubusercontent.com/42773655/66575129-b4e33180-eb75-11e9-9958-0c343d655f3e.png)

However, some slovakian developers from wazer.sk optimized the code and implemented the highway vignettes so it calculates correctly now.
![image](https://user-images.githubusercontent.com/42773655/66575210-d6dcb400-eb75-11e9-9ece-745cd7d88063.png)

here is the link to the updated map:
[Updated routing map](https://www.waze.com/sk/livemap?rp_subscription=*)

UPDATE: I was in contact with the guys who did this and they just said it only uses a paramater (in the link I think) that ignores restrictions such as highway vignettes (for Slovakia).

**Comment by welo78** [comment]
@sretalla I just got a response on the issue on Home Assistant github and here it is :

> The Autor of WazeRouteCalculator should publish a new version to pypi.org. The current version 0.10 does not include the AVOID_SUBSCRIPTION_ROAD functionality.
> 
> After that home assistant can be changed to use the never version.
> 
> So please ask the author of https://github.com/kovacsbalu/WazeRouteCalculator to make a new release.



[Home assistant waze route calculator issue](https://github.com/home-assistant/home-assistant/issues/27400#issuecomment-541353199)

I do not know how this works actually and what do they talk about. I would gladly like to solve this issue for you but IDK how can I help with this.

**Comment by mrand** [comment]
@sretalla It appears that there hasn't been an official release since March:

https://github.com/kovacsbalu/WazeRouteCalculator/releases

Presumably if it was updated, then https://pypi.org/project/WazeRouteCalculator/#history could be updated, and then Home Assistant could update.

**Comment by kovacsbalu** [comment]
Hi All, you are right. This feature has not been released. Coming soon :) (i hope i have time on Monday)

**Comment by welo78** [comment]
@kovacsbalu Hello, did you get to it yet to fix the issue ? So I am assuming all is needed is to publish a new release yeah ?

I say this like its a piece of cake but all my knowledge is just theoretical, IDK how much work is needed to actually release it so please do not stone me to death.

**Comment by kovacsbalu** [comment]
Busy days....and also waiting for #50

**Comment by kovacsbalu** [comment]
Done.
https://pypi.org/project/WazeRouteCalculator/0.11/

**Comment by hmmbob** [comment]
I am working on the integration in Home Assistant, and while AVOID_TOLL works fine, the AVOID_SUBSCRIPTION_ROADS throws an error when set to True. Any idea why?

> Error on retrieving data: Error: No enum constant linqmap.routing.interfaces.RoutingOption.AVOID_SUBSCRIPTION_ROADS

**Comment by welo78** [comment]
@hmmbob how can I update it manually ? I must wait for next release of HA no ?

**Comment by hmmbob** [comment]
That is the easiest option, just to wait. You can do the code changes locally yourself too if you are comfortable with that - use the pull requests in this location and HA.
