### ISSUE TITLE
LGPL-3 or GPL-3

### ISSUE THREAD

**Issue by onkelbeh** [kovacsbalu/WazeRouteCalculator#53]
Hi Kovács,

Thanks for your work.

I am using your component `WazeRouteCalculator` for my [Home Assistant Overlay for Gentoo Linux](https://github.com/onkelbeh/HomeAssistantRepository) and I am confused about your license selection.

You state `LGPL-3` on Github Project Page, and `GPL-3` in setup-py and on Pypi. These are different but should be unique.

I have now assumed that `GPL-3`is the correct License for your package, 3 against 1, just wanted to ask for clarification.

You can find your component at my Overlay at: https://github.com/onkelbeh/HomeAssistantRepository/tree/master/dev-python/WazeRouteCalculator.

Please drop me a note if you find something wrong.

 \B.

**Comment by kovacsbalu** [comment]
Thanks, @onkelbeh fixed.
