### ISSUE TITLE
log_lvl

### ISSUE THREAD

**Issue by erikwachters** [kovacsbalu/WazeRouteCalculator#54]
Hi,

I have the following warning in my home assistant log:

`WARNING (SyncWorker_9) [WazeRouteCalculator.WazeRouteCalculator] log_lvl is deprecated please check example.py`

**Comment by kovacsbalu** [comment]
Hi, as I can see you are using from home assitant?
Probably your module set `log_lvl` arg but this is deprecated since 0.10.
