### ISSUE TITLE
Included regions

### ISSUE THREAD

**Issue by victorccaldas** [kovacsbalu/WazeRouteCalculator#55]
Why are the only regions included for traffic and routing optimization Europe, North America and Israel?
Would be great to see other territories approached as well, such as Brazil or South America.

**Comment by kovacsbalu** [comment]
Hello,
As I know Waze has 3 servers, United States/North America, Israel, and Rest of World. So when you sets region as US, NA, IL, EU, or AU, it corresponds to these servers.
Probably we should remove the AU and use one of the 3 server and custom base coordinate.
Feel free to create a pull request. :)

**Comment by victorccaldas** [comment]
Oh ok.
Don't know about it's servers, but it (the mobile app) works perfectly here in Brazil. 
Also I didn't understand what AU stands for, in between the areas you mentioned?

**Comment by hmmbob** [comment]
Australia. 

Basically what he is saying, is that it only refers to which backend servers the component uses with Waze (Waze has 3 servers, US, Israel, Rest-Of-World). The logic with country codes is to assist the code in choosing a nearby server, but it doesn't really impact your usage.

You can just use the component without bothering (but might want to use a server close to you)
