### ISSUE TITLE
Calculate a time and distance matrix from WazeRouteCalculator

### ISSUE THREAD

**Issue by JosephDqs** [kovacsbalu/WazeRouteCalculator#67]
Hello, 
As I understand right now, the route is calculated from the date you send the request and the time_delta is only minutes you add to your current time.

Is there a way to calculate for example from 6:00 am to 8 pm the averages time and distance for each 10 minutes intervals on one day ?

Thanks for answering,

**Comment by kovacsbalu** [comment]
Hi @JosephDqs, 
waze routing server request has an `at` argument and as I saw in waze editor this works with negative numbers also.
So you can set it to now -X minute.
You can create a for loop with your time range.

**Comment by JosephDqs** [comment]
So basically to normalize the thing,
 I can take the **current hour** and do put to argument  "**hour I want**  - **current hour**"
right ?

**Comment by kovacsbalu** [comment]
Almost, you need to set minutes in `at` argument.
