### ISSUE TITLE
using behind proxy

### ISSUE THREAD

**Issue by Rmfjd1978** [kovacsbalu/WazeRouteCalculator#68]
I want to use wazeroutecalculator but i want to specify a proxy to use in the request made by the lib. How can i do that.

**Comment by kovacsbalu** [comment]
Hi @Rmfjd1978, you can use `ENV` vars as `requests` as the doc writes: https://requests.readthedocs.io/en/latest/user/advanced/?highlight=http_proxy#proxies

**Comment by Rmfjd1978** [comment]
but in my case this is to use in my company and for testing in my personal computer they don't give me the proxy, so i need to override you request.
