### ISSUE TITLE
Waze integration errors when 'overseas', prefer simple warnings or no errors

### ISSUE THREAD

**Issue by vingerha** [kovacsbalu/WazeRouteCalculator#70]
### The problem

I have a integration between a device (phone) and home location, thus indicating the amount of time from home.
This works fine but not when the device is on an island, i.e. the example I have is when the device is on Corsica and the home address is on France mainland. Now, I am OK that this does not work but it should not throw unnecessary errors.
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/waze_travel_time/sensor.py", line 169, in update
    self._waze_data.update()
  File "/usr/src/homeassistant/homeassistant/components/waze_travel_time/sensor.py", line 216, in update
    routes = params.calc_all_routes_info(real_time=realtime)
  File "/usr/local/lib/python3.10/site-packages/WazeRouteCalculator/WazeRouteCalculator.py", line 209, in calc_all_routes_info
    results = {"%s-%s" % (route['routeType'][0], route['shortRouteName']): self._add_up_route(route['results' if 'results' in route else 'result'], real_time=real_time, stop_at_bounds=stop_at_bounds) for route in routes}
  File "/usr/local/lib/python3.10/site-packages/WazeRouteCalculator/WazeRouteCalculator.py", line 209, in <dictcomp>
    results = {"%s-%s" % (route['routeType'][0], route['shortRouteName']): self._add_up_route(route['results' if 'results' in route else 'result'], real_time=real_time, stop_at_bounds=stop_at_bounds) for route in routes}
IndexError: list index out of range
```

### What version of Home Assistant Core has the issue?

2022.8.4 (1 as well)

### What was the last working version of Home Assistant Core?

none

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

waze

**Comment by kovacsbalu** [comment]
Hi @vingerha, this error came from HA waze_travel_time plugin. Not from my lib.
Please open a ticket here: [ha-waze_travel_time](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+waze_travel_time%22)

**Comment by vingerha** [comment]
I did open it there and was pointed to this page.... sigh

**Comment by hmmbob** [comment]
@kovacsbalu the error is raised by your lib. Check the last 4 lines of the log.

**Comment by kovacsbalu** [comment]
Right, thx @hmmbob.

**Comment by kovacsbalu** [comment]
@vingerha can you please give coordinates to reproduce this error?

**Comment by vingerha** [comment]
... not willing to share either of them exactly as private
But, it happened when the phone was on Corsica (42.435325, 9.451002) with connection to our home on the French mainland (43.68534085945735, 7.235257349163553). I have three other waze integrations that work fine when both are on the mainland

**Comment by kovacsbalu** [comment]
Right, I dont want to know your private address. :)
It works with these coords
```
From: 42.435325, 9.451002 - to: 43.68534085945735, 7.235257349163553
Start coords: (42.435325, 9.451002)
End coords: (43.68534085945735, 7.235257349163553)
Min     Max
506.63  1461.85 minutes
281.03  603.14 km
```

with this code:


```from_address = '42.435325, 9.451002'
to_address = '43.68534085945735, 7.235257349163553'
route = WazeRouteCalculator.WazeRouteCalculator(from_address, to_address)
route.calc_all_routes_info()
```

**Comment by vingerha** [comment]
Darn, so you need exact coordinates where it goes wrong. 
That will be difficult as trial and error is not what I want to do...also makes no sense as that is not a real-life situation.
I searched a bit further and the start location in HA was exactly 42,44 / 9,45 (very few digits indeed)

**Comment by vingerha** [comment]
Well, you can only do as much. I cannot reproduce it anylonger as not in Corsica

**Comment by sretalla** [comment]
(42.6976289, 9.4442031)
That's the coordinates of a hotel in Bastia... Should be enough if anyone wants to look into it.

**Comment by Woyken** [comment]
I just ran into the same problem when using home assistant.
Errors show up when coordinates are nearby or exactly the same for `from` and `to`

`KeyError: 'shortRouteName'`

Coordinates that cause this:
from:   x:25.268346 y:54.673556         (54.673556, 25.268346)
to:       x:25.268346 y:54.673556         (54.673556, 25.268346)
region: EU

I can see that there is already a [fix](https://github.com/kovacsbalu/WazeRouteCalculator/commit/9e1d5a8ee780c5b041be449b8f003a53fd3e1fe7), just not released

related issue on home assistant side:
<https://github.com/home-assistant/core/issues/93240>

![image](https://github.com/kovacsbalu/WazeRouteCalculator/assets/13166802/a8c3c748-0878-4773-b70c-e3fdcabea4f6)
![image](https://github.com/kovacsbalu/WazeRouteCalculator/assets/13166802/6830b7db-1b93-40f8-abf2-5ccd237793c0)
