### ISSUE TITLE
Release latest 3 commits since 0.15

### ISSUE THREAD

**Issue by eifinger** [kovacsbalu/WazeRouteCalculator#71]
Hi @kovacsbalu , I just saw that the Homeassistant Integration using this lib shows the following error:

```
File "/usr/local/lib/python3.10/site-packages/WazeRouteCalculator/WazeRouteCalculator.py", line 209, in calc_all_routes_info
    results = {"%s-%s" % (route['routeType'][0], route['shortRouteName']): self._add_up_route(route['results' if 'results' in route else 'result'], real_time=real_time, stop_at_bounds=stop_at_bounds) for route in routes}
IndexError: list index out of range
```

Before digging deeper I would like to use your latest changes which might fix this issue.

Could you please create a new release?
Thank you

**Comment by elad-bar** [comment]
seems that the api got broken, please read comment at HA GitHub https://github.com/home-assistant/core/issues/66058
