### ISSUE TITLE
ValueError: Unknown level:

### ISSUE THREAD

**Issue by jayfiro** [kovacsbalu/WazeRouteCalculator#9]
When running:

import WazeRouteCalculator

from_address = 'Budapest, Hungary'
to_address = 'Gyor, Hungary'
region = 'EU'

route = WazeRouteCalculator.WazeRouteCalculator(from_address, to_address, region)

The last line gives ValueError: Unknown level: 'EU'

**Comment by kovacsbalu** [comment]
Hi @jayfiro, sorry but I cannot reproduce. Are you using git master branch?

**Comment by Scimonster** [comment]
@kovacsbalu Maybe update the version on pip?

**Comment by kovacsbalu** [comment]
Yes, just waiting a bit for pr. :)

**Comment by Scimonster** [comment]
PR submitted. :) #10

**Comment by kovacsbalu** [comment]
Yep, I also got a mail about it. :)

**Comment by kovacsbalu** [comment]
@jayfiro please check new 0.4 version. [https://pypi.python.org/pypi/WazeRouteCalculator/0.4](url)

**Comment by jayfiro** [comment]
@kovacsbalu it works now with version 0.4.
